# Generated by Django 4.2.15 on 2024-08-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cook_day_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="recipes/"),
        ),
    ]
